### ISSUE TITLE
STS 환경 설정, 형상 관리

### ISSUE THREAD

**Issue by chessta0126** [chessta0126/festivalBooking#2]
## STS 환경 설정
- [ ] STS 설치
- [ ] Marketplace에서 web tools install 설치
- [ ] 인코딩 방식 설정 (UTF-8)
- [ ] 프로젝트 만들기

### 2. JSON 확인 : @ResponseBody + String return
- [ ] **1) MemoApplication.java의 @SpringBootApplication 위에 어노테이션 추가**
```
@EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class})
```

- [ ] **2) debug 에러 해결(서버를 일단 한 번이라도 켜야 함)**
```
일단 서버 실행하고 프로젝트 우측 클릭 > Run As > Run Configurations > Arguments 탭 첫번째에 문구 추가
--debug
```

- [ ] **3) main에 TestController 클래스 만들기 + @Controller**

### 3. JSP 동작 확인 : String return
- [ ] **1) gradle에 dependency 추가**
```
implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
implementation group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: '2.0.0'
```
-> gradle refresh

- [ ] **2) application.properties 파일 삭제 후 application.yml 추가(먼저 읽힘)**
-> new -> file -> application.yml (탭 정렬 맞추기)
```
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
```

- [ ] **3) src> main> webapp> WEB-INF> jsp 폴더 만들기**

### 4. DB 연동 확인 : 어노테이션 제거, DB 설정 java, yml 접속정보 추가, config, logback.xml

- [ ] **1) MemoApplication.java의 @SpringBootApplication 위에 어노테이션 제거**
```
// @EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class})
```

- [ ] **2) config (베이스 패키지 안에 config 패키지 생성)**
main에 com.memo.config 패키지 -> DatabaseConfig 클래스 만들기
```
@Configuration
@MapperScan(basePackages="com.memo.*")
public class DatabaseConfig {

 @Bean
    public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
        SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);

        Resource[] res = new PathMatchingResourcePatternResolver().getResources("classpath:mappers/*Mapper.xml"); //  앞: 경로, *뒤: 파일 이름 이렇게 끝나야 함
        sessionFactory.setMapperLocations(res);

        return sessionFactory.getObject();
    }
}
```

- [ ] **3) logback - 쿼리 수행 로그 세팅**
src/main/resources -> logback-spring.xml에 아래 코드 복붙
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">

    <!-- Appenders -->
    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <Pattern>%d %5p [%c] %m%n</Pattern>
        </encoder>
    </appender>

    <!-- Logger -->
    <logger name="★베이스패키지★" level="DEBUG" appender-ref="console" />

    <!-- Root Logger -->
    <root level="info">
        <appender-ref ref="console" />
    </root>
</configuration>
```

- [ ] **4) yml 정보 최종 (탭 정렬이 안 맞으면 읽을 수 없으므로 주의)**
```
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:★DB 포트번호★/★DB명★?★타임존 제거★characterEncoding=UTF-8
    username: root
    password: root ★DB 비밀번호★
```

- [ ] **5) postMapper.xml 생성**

### 형상 관리
- [ ] repository 만들기
- [ ] sourcetree를 통해 github 연동
- [ ] develop, master 브랜치 생성
- [ ] 커밋 & push
- [ ] 크롬 웹스토어 -> zenhub 검색 & 다운로드

**Comment by chessta0126** [comment]
* DB연동 에러
yml에서 localhost를 8080 port로 착각하고 잘못 써서 발생

MySQL DB에서 스키마를 생성할 때, 카멜케이스로 써도 모두 소문자로 나온다.
이 경우, STS에서 카멜로 써도 대소문자 관계없이 DB 연동이 되는 것을 확인

**Comment by chessta0126** [comment]
* 파일 용량 -   yml에서 최대 10MB로 확장
```
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
```
